### PR TITLE
Hex to HSL

### PR DESCRIPTION
**Pull request by Myles2**
I changed the Hex colors to the HSL format.

### CODE REVIEW

**Comment by RayRedGoose** [comment]
Thank you for attention to our project. Unfortunately, we don't accept PRs from not contributors.

**Comment by JamesRexMiller4** [comment]
Hey @Myles2 thanks for this PR. This repo is currently a group project for the students of the Turing School Front End Program, and our instructors have informed us that we cannot allow outside contributors until after we have submitted it for review/grading. However, in a week or so I would be more than happy to review this PR and merge it in.

**Comment by Myles2** [comment]
@JamesRexMiller4 oh ok no problem, I was just looking for projects to contribute to during Hacktoberfest. Just as a heads up I found your project on issuehub.io

**Comment by JamesRexMiller4** [comment]
@Myles2 yeah this same thing happened to another group in our class. Thanks for the heads up, not sure how this repo got on there. For the other group they used one of the new issue labels that are meant to draw attention to their repos for HacktoberFest, but I'll scope it out. 

Ironically enough, your PR is 100% in accordance with a lesson that we went over regarding HSL over HEX/RGB. So you're good.....almost too good : )

**Comment by Myles2** [comment]
@JamesRexMiller4 That makes sense, **I found the project through a CSS issue label** (on issuehub.io) I'm not really sure how they find their projects I assumed it be some sort of web scraping on Github, but when I checked their site it seems like each project is hardcoded in but there's probably something I'm missing. 

I'm sure after this October PR craze you won't get that many more random contributors but the best thing I can suggest to deter others is probably to **add a description of what this project is for and who can contribute in the README.**

Also **Thanks for the compliment** 👍 :) Honestly it was really easy as soon as I opened it up in VS code I hovered over the color clicked its former hex icon and it circulated to RGB then HSL.

**Anyways good luck on your project I hope you guys PASS 💯**

**Pull request closed without merging**
